rules:
  - ''
  - ''
  - '&a&l>> &b&lRegulamin &a&l<<'
  - ''
  - '&71. &aAdministracja nie przywraca utraconych itemow.'
  - '&72. &aZakaz uzywania cheatow!'
  - '&73. &aZakaz spamowania na chacie serwera.'
  - '&74. &aZakaz reklamowania innych serwerow!'
  - '&75. &aZakaz podszywania sie pod administracje!'
  - '&76. &aZakaz uzywania wulgaryznow oraz slow typu n-word!'
  - '&77. &aZakaz uzywania maszyn i innych rzeczy do crashowania serwera i/lub kopiowania przedmiotow!'
  - '&78. &aProsi sie o nie naduzywanie duzych liter.'
  - '&79. &aProsi sie o nie floodowanie na chacie.'
  - '&710. &aSzanuj innych graczy serwera oraz administracje!'
  - ''
  - '&6&lNieznajomosc regulaminu nie zwalnia z obowiazku przestrzegania go!!!'
  - ''
  - ''