player_null: "<dark_red><bold>[!] <grey>- <grey>Podany gracz nie istnieje!"
chat_wrong: "<blue><bold>[!] <grey>- poprawne uzycie: <gold>/chat <green>on<grey>/<green>off<grey>/<green>clear"
chat_already_on: "<red><bold>[!] <grey>- Chat jest juz wlaczony!"
chat_on: "<gold><bold>[!] <grey>- Chat zostal <green><bold>wlaczony!"
chat_already_off: "<red><bold>[!] <grey>- Chat jest juz wylaczony!"
chat_off: "<gold><bold>[!] <grey>- Chat zostal <red><bold>wylaczony!"
fly_off: "<gold><bold>[!] <grey>- <red>Wylaczyles <grey>latanie"
fly_on: "<gold><bold>[!] <grey>- <green>Wlaczyles <grey>latanie"
fly_off_other: "<gold><bold>[!] <grey>- <red>Wylaczyles <grey>latanie dla %target%"
fly_other_off_me: "<red><bold>[!] <grey>- Osoba %player% <red>Wylaczyla <grey>tobie latanie"
fly_on_other: "<gold><bold>[!] <grey>- <green>Wlaczyles <grey>latanie dla gracza %target%"
fly_other_on_me: "<red><bold>[!] <grey>- Osoba %player% <green>Wlaczyla <grey>tobie latanie"
